version: '3'
name: doan-shop
services:
  web:
    image: nginx:latest
    ports:
      - 1103:80
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
      
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/app

  db:
    image: mariadb:latest
    volumes:
      - mariadb-vol:/var/lib/mysql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=0
      - MARIADB_ROOT_PASSWORD=CookieGMVN2007

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - 8918:80
    links:
      - db

volumes:
  mariadb-vol: